[2023-10-17 16:18:12,098] DEBUG in users: SELECT * FROM users
[2023-10-17 16:18:15,218] DEBUG in users: SELECT * FROM users
[2023-10-27 03:58:31,410] INFO in uvicorn.error: Started server process [1177]
[2023-10-27 03:58:31,410] INFO in uvicorn.error: Waiting for application startup.
[2023-10-27 03:58:31,411] INFO in uvicorn.error: Application startup complete.
[2023-10-27 03:59:29,957] INFO in uvicorn.error: Shutting down
[2023-10-27 03:59:30,060] INFO in uvicorn.error: Finished server process [1177]
[2023-10-27 03:59:30,063] ERROR in uvicorn.error: Traceback (most recent call last):
  File "/home/liam/.local/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2023-10-27 04:01:36,086] INFO in uvicorn.error: Started server process [2106]
[2023-10-27 04:01:36,087] INFO in uvicorn.error: Waiting for application startup.
[2023-10-27 04:01:36,087] INFO in uvicorn.error: Application startup complete.
[2023-10-27 04:06:43,976] INFO in uvicorn.error: Shutting down
[2023-10-27 04:06:44,077] INFO in uvicorn.error: Finished server process [2106]
[2023-10-27 04:06:44,078] ERROR in uvicorn.error: Traceback (most recent call last):
  File "/home/liam/.local/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

[2023-10-27 04:10:57,672] INFO in uvicorn.error: Started server process [2213]
[2023-10-27 04:10:57,673] INFO in uvicorn.error: Waiting for application startup.
[2023-10-27 04:10:57,684] INFO in uvicorn.error: Application startup complete.
[2023-10-27 04:16:12,129] INFO in uvicorn.error: Shutting down
[2023-10-27 04:16:12,230] INFO in uvicorn.error: Finished server process [2213]
[2023-10-27 04:16:12,231] ERROR in uvicorn.error: Traceback (most recent call last):
  File "/home/liam/.local/lib/python3.10/site-packages/starlette/routing.py", line 686, in lifespan
    await receive()
  File "/usr/lib/python3/dist-packages/uvicorn/lifespan/on.py", line 135, in receive
    return await self.receive_queue.get()
  File "/usr/lib/python3.10/asyncio/queues.py", line 159, in get
    await getter
asyncio.exceptions.CancelledError

